# Major Keys
a_flat_major = ["Ab", "Bb", "C", "Db", "Eb", "F", "G"]
a_major = ["A", "B", "C#", "D", "E", "F#", "G#"]
b_flat_major = ["Bb", "C", "D", "Eb", "F", "G", "A"]
b_major = ["B", "C#", "D#", "E", "F#", "G#", "A#"]
c_major = ["C", "D", "E", "F", "G", "A", "B"]
d_flat_major = ["Db", "Eb", "F", "Gb", "Ab", "Bb", "C"]
d_major = ["D", "E", "F#", "G", "A", "B", "C#"]
e_flat_major = ["Eb", "F", "G", "Ab", "Bb", "C", "D"]
e_major = ["E", "F#", "G#", "A", "B", "C#", "D#"]
f_major = ["F", "G", "A", "Bb", "C", "D", "E"]
f_sharp_major = ["F#", "G#", "A#", "B", "C#", "D#", "E#"]
g_flat_major = ["Gb", "Ab", "Bb", "Cb", "Db", "Eb", "F"]
g_major = ["G", "A", "B", "C", "D", "E", "F#"]

# Natural Minor Keys (Relative to Major Keys)
a_minor = ["A", "B", "C", "D", "E", "F", "G"]
b_flat_minor = ["Bb", "C", "Db", "Eb", "F", "Gb", "Ab"]
b_minor = ["B", "C#", "D", "E", "F#", "G", "A"]
c_minor = ["C", "D", "Eb", "F", "G", "Ab", "Bb"]
d_minor = ["D", "E", "F", "G", "A", "Bb", "C"]
e_flat_minor = ["Eb", "F", "Gb", "Ab", "Bb", "Cb", "Db"]
e_minor = ["E", "F#", "G", "A", "B", "C", "D"]
f_minor = ["F", "G", "Ab", "Bb", "C", "Db", "Eb"]
g_minor = ["G", "A", "Bb", "C", "D", "Eb", "F"]

# Additional Keys (Enharmonic Equivalents)
a_sharp_minor = ["A#", "B#", "C#", "D#", "E#", "F#", "G#"]
c_sharp_major = ["C#", "D#", "E#", "F#", "G#", "A#", "B#"]
c_sharp_minor = ["C#", "D#", "E", "F#", "G#", "A", "B"]
d_flat_major = ["Db", "Eb", "F", "Gb", "Ab", "Bb", "C"]
d_sharp_minor = ["D#", "E#", "F#", "G#", "A#", "B", "C#"]
f_sharp_major = ["F#", "G#", "A#", "B", "C#", "D#", "E#"]
g_flat_minor = ["Gb", "Ab", "Bbb", "Cb", "Db", "Ebb", "Fb"]
g_sharp_minor = ["G#", "A#", "B", "C#", "D#", "E", "F#"]